variables:
  - name: ArmTemplateRoot
    value: '$(Build.SourcesDirectory)\Resources\ArmTemplates' 

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v1.6.12
    endpoint: 'GitHub (ESFA)'

pr:
  branches:
    include:
    - master

jobs:

  - template: AzureDevOpsTemplates/Build/dfc-arm-build.yml@dfc-devops
    parameters:
      ArmTemplateRoot: $(ArmTemplateRoot)