parameters:
  AzureSubscription: ''
  Environment: ''
  EnvironmentTag: ''
  ParentBusinessTag: ''
  ResourceGroup: ''
  ServiceOfferingTag: ''
  AzurePrefix: ''

jobs:
- deployment: DeployTo${{ parameters.Environment }}
  pool:
    name: 'NCS - CI and CD'
  environment: ${{ parameters.Environment }}
  strategy:
    runOnce:
      deploy:
        steps:
        - template: AzureDevOpsTemplates/Deploy/StepTemplates/dfc-arm-deploy.yml@dfc-devops
          parameters:
            ArmTemplateRoot: '$(Pipeline.Workspace)/Dfc.ServiceTaxonomy.Shared.Resources.ArmTemplates'
            AzureSubscription: ${{ parameters.AzureSubscription }}
            EnvironmentTag: ${{ parameters.EnvironmentTag }}
            ParentBusinessTag: ${{ parameters.ParentBusinessTag }}
            ResourceGroup: ${{ parameters.ResourceGroup }}
            ServiceOfferingTag: ${{ parameters.ServiceOfferingTag }}
- job: DeployMonitor
  dependsOn: 
  - DeployTo${{ parameters.Environment }}
  pool:
    name: 'NCS - CI and CD'
  steps:
  - task: DownloadPipelineArtifact@2
    displayName: Download built distribution
    inputs:
      source: 'specific'
      project: '$(System.TeamProjectId)'
      # this is the dfc-azure-monitor-to-slack pipeline
      pipeline: 1783
      # ############
      runVersion: 'latestFromBranch'
      runBranch: 'refs/heads/master'
      artifactName: 'DFC.AzureMonitorToSlack'
      # this is the last successful build of the dfc-azure-monitor-to-slack pipeline
      buildid: 242189
      # you will need to update this buildId with any new build of dfc-azure-monitor-to-slack that you want picked up
      path: '$(Pipeline.Workspace)' 
  - task: AzureFunctionApp@1
    displayName: 'Azure Function App Deploy: ${{ parameters.AzurePrefix }}-mon-fa'
    inputs:
      azureSubscription: '${{ parameters.AzureSubscription }}'
      appType: functionApp
      appName: '${{ parameters.AzurePrefix }}-mon-fa'
      package: '$(Pipeline.Workspace)/slack_azure_function.zip'


