parameters:
  AzureSubscription: ''
  Environment: ''
  EnvironmentTag: ''
  ParentBusinessTag: ''
  ResourceGroup: ''
  ServiceOfferingTag: ''

jobs:
- deployment: DeployTo${{ parameters.Environment }}
  pool:
    name: 'NCS - CI and CD'
  environment: ${{ parameters.Environment }}
  strategy:
    runOnce:
      deploy:
        steps:
        - template: AzureDevOpsTemplates/Deploy/StepTemplates/dfc-arm-deploy.yml@dfc-devops
          parameters:
            ArmTemplateRoot: '$(Pipeline.Workspace)/Dfc.ServiceTaxonomy.Shared.Resources.ArmTemplates'
            AzureSubscription: ${{ parameters.AzureSubscription }}
            EnvironmentTag: ${{ parameters.EnvironmentTag }}
            ParentBusinessTag: ${{ parameters.ParentBusinessTag }}
            ResourceGroup: ${{ parameters.ResourceGroup }}
            ServiceOfferingTag: ${{ parameters.ServiceOfferingTag }}
- job: DeployMonitor
  pool:
    name: 'NCS - CI and CD'
  steps:
  - task: DownloadPipelineArtifact@2
    displayName: Download built distribution
    inputs:
      source: 'specific'
      project: '$(System.TeamProjectId)'
      pipeline: 1783
      runVersion: 'latestFromBranch'
      runBranch: 'refs/heads/master'
      artifactName: 'DFC.AzureMonitorToSlack'
      itemPattern: '*.zip'
      buildid: 242189

